db_host: localhost
postgresql_databases:
  - name: nsl
postgresql_users:
  - name: example_user
    password: supersecure
    state: absent
  - name: nsl
    password: nsl
    role_attr_flags: SUPERUSER,LOGIN
  - name: webmoss
    role_attr_flags: SUPERUSER
  - name: moss
    role_attr_flags: SUPERUSER
  - name: web
    role_attr_flags: SUPERUSER
  - name: read_only
  - name: nsl
    password: nsl
    role_attr_flags: SUPERUSER,LOGIN
  - name: nslrds
    password: supersecure
    role_attr_flags: SUPERUSER,LOGIN